#spring.application.name=SpringExtensao

#driver
spring.datasource.driver-class-name=org.postgresql.Driver
#string de conexão
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.
spring.datasource.username=postgres.umczjvdwpiigsdhkabxw
spring.datasource.password=rmGKKVaEBgpIoO2Y
#auto geração do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.P