-- Dummy Data

-- Tipos de Oportunidade
INSERT INTO tipo (nome) VALUES ('PROJETO') ON CONFLICT DO NOTHING;
INSERT INTO tipo (nome) VALUES ('CURSO') ON CONFLICT DO NOTHING;
INSERT INTO tipo (nome) VALUES ('EVENTO') ON CONFLICT DO NOTHING;
INSERT INTO tipo (nome) VALUES ('PROGRAMA') ON CONFLICT DO NOTHING;
INSERT INTO tipo (nome) VALUES ('PRESTACAO_SERVICO') ON CONFLICT DO NOTHING;


-- Papéis
INSERT INTO papel (nome) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO papel (nome) VALUES ('COORDENADOR') ON CONFLICT DO NOTHING; -- docente
INSERT INTO papel (nome) VALUES ('DIRETOR') ON CONFLICT DO NOTHING; -- discente
INSERT INTO papel (nome) VALUES ('VICE-DIRETOR') ON CONFLICT DO NOTHING; -- discente
INSERT INTO papel (nome) VALUES ('TESOUREIRO') ON CONFLICT DO NOTHING; -- discente
INSERT INTO papel (nome) VALUES ('MEMBRO') ON CONFLICT DO NOTHING; -- discente